import { Author, MedicalCase } from '@/types';
import { generateId } from '@/lib/utils';

export const DEFAULT_AUTHOR: Author = {
  id: 'auth-001',
  name: 'Dr. Aryan Mehta',
  role: 'Medical Student',
  specialty: 'General Medicine',
  institution: 'AIIMS Delhi',
  casesCreated: 8,
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aryan',
};

const today = new Date().toISOString().split('T')[0];

export const MOCK_CASES: MedicalCase[] = [
  {
    id: 'case-001',
    title: 'Acute Myocardial Infarction in a 58-year-old Male',
    specialty: 'Cardiology',
    status: 'Published' as const,
    tags: ['STEMI', 'ACS', 'Chest Pain'],
    difficulty: 'Intermediate',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-001',
      age: 58,
      gender: 'Male',
      occupation: 'Bank Manager',
      location: 'New Delhi',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Severe retrosternal chest pain radiating to left arm for 2 hours',
      historyOfPresentingIllness: 'Patient reports sudden onset of severe crushing chest pain while at work, associated with sweating and nausea.',
      pastMedicalHistory: ['Hypertension', 'Hyperlipidemia', 'Diabetes'],
      familyHistory: 'Father had MI at 60',
      socialHistory: 'Smokes 1 pack/day for 30 years, occasional alcohol',
      allergies: ['Penicillin'],
      currentMedications: ['Amlodipine 5mg', 'Atorvastatin 20mg', 'Metformin 500mg'],
      reviewOfSystems: {
        Cardiovascular: 'Positive for chest pain, no palpitations',
        Respiratory: 'No dyspnea',
        Gastrointestinal: 'Nausea present, no vomiting',
        Neurological: 'No headache, no weakness',
        Musculoskeletal: 'No joint pain',
        Dermatological: 'No rashes',
      },
    },
    examinationFindings: {
      generalAppearance: 'Anxious, diaphoretic',
      vitalSigns: {
        bloodPressure: '150/90 mmHg',
        heartRate: '110 bpm',
        respiratoryRate: '20/min',
        temperature: '98.6°F',
        oxygenSaturation: '98%',
        weight: '85 kg',
        height: '170 cm',
        bmi: '29.4',
      },
      systemicExamination: {
        cardiovascular: 'Tachycardic, no murmurs',
        respiratory: 'Clear bilaterally',
        gastrointestinal: 'Soft, non-tender',
        neurological: 'Alert and oriented',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-001',
        type: 'Lab',
        name: 'Troponin I',
        result: '1.2 ng/mL',
        normalRange: '<0.04 ng/mL',
        date: today,
        interpretation: 'Elevated, consistent with myocardial injury',
      },
      {
        id: 'inv-002',
        type: 'Imaging',
        name: 'ECG',
        result: 'ST elevation in leads II, III, aVF',
        normalRange: '',
        date: today,
        interpretation: 'Inferior STEMI',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Acute Inferior STEMI',
      differentialDiagnoses: ['Pericarditis', 'Pulmonary Embolism', 'GERD'],
      finalDiagnosis: 'Acute Inferior Wall Myocardial Infarction',
      treatmentPlan: 'Emergency PCI, Aspirin 325mg loading, Heparin infusion',
      medications: [
        { name: 'Aspirin', dose: '325mg', frequency: 'Once daily', duration: 'Lifelong' },
        { name: 'Clopidogrel', dose: '75mg', frequency: 'Once daily', duration: '12 months' },
      ],
      followUp: 'Cardiology clinic in 2 weeks, then monthly',
      prognosis: 'Good with timely revascularization',
      learningPoints: [
        'Recognize typical STEMI symptoms',
        'Time is muscle - urgent reperfusion',
        'Risk factor modification',
      ],
    },
  },
  {
    id: 'case-002',
    title: 'Type 2 Diabetes Mellitus New Onset',
    specialty: 'Endocrinology',
    status: 'In Progress' as const,
    tags: ['DM2', 'Hyperglycemia', 'Polyuria'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-002',
      age: 45,
      gender: 'Female',
      occupation: 'Teacher',
      location: 'Gurugram',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Increased thirst and frequent urination for 1 month',
      historyOfPresentingIllness: 'Patient reports polyuria, polydipsia, and unintentional weight loss of 5 kg.',
      pastMedicalHistory: [],
      familyHistory: 'Mother has Type 2 DM',
      socialHistory: 'No smoking, no alcohol',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {
        Cardiovascular: 'No chest pain',
        Respiratory: 'No cough',
        Gastrointestinal: 'No abdominal pain',
        Neurological: 'No numbness',
        Musculoskeletal: 'No pain',
        Dermatological: 'No itching',
      },
    },
    examinationFindings: {
      generalAppearance: 'Well-nourished, alert',
      vitalSigns: {
        bloodPressure: '130/80 mmHg',
        heartRate: '88 bpm',
        respiratoryRate: '16/min',
        temperature: '98.4°F',
        oxygenSaturation: '99%',
        weight: '78 kg',
        height: '160 cm',
        bmi: '30.5',
      },
      systemicExamination: {
        cardiovascular: 'Normal S1 S2',
        respiratory: 'Clear',
        gastrointestinal: 'Soft',
        neurological: 'Normal reflexes',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-003',
        type: 'Lab',
        name: 'Fasting Blood Sugar',
        result: '180 mg/dL',
        normalRange: '70-100 mg/dL',
        date: today,
        interpretation: 'Elevated',
      },
      {
        id: 'inv-004',
        type: 'Lab',
        name: 'HbA1c',
        result: '8.5%',
        normalRange: '4.0-5.6%',
        date: today,
        interpretation: 'Consistent with diabetes',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Type 2 Diabetes Mellitus',
      differentialDiagnoses: ['Type 1 DM', 'Stress hyperglycemia', 'Cushing syndrome'],
      treatmentPlan: 'Lifestyle modifications + Metformin',
      medications: [
        { name: 'Metformin', dose: '500mg', frequency: 'Twice daily', duration: 'Ongoing' },
      ],
      followUp: 'Monthly visits initially',
      prognosis: 'Good with compliance',
      learningPoints: [
        'Classic symptoms of diabetes',
        'Importance of HbA1c',
        'Lifestyle first approach',
      ],
    },
  },
  {
    id: 'case-003',
    title: 'Community Acquired Pneumonia',
    specialty: 'Pulmonology',
    status: 'Review',
    tags: ['CAP', 'Pneumonia', 'Infection'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-003',
      age: 35,
      gender: 'Male',
      occupation: 'Engineer',
      location: 'Noida',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Cough with fever for 5 days',
      historyOfPresentingIllness: 'Productive cough with rusty sputum, high-grade fever, and right-sided chest pain.',
      pastMedicalHistory: [],
      familyHistory: 'No similar illness',
      socialHistory: 'No smoking, occasional alcohol',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {
        Cardiovascular: 'No chest pain',
        Respiratory: 'Dyspnea on exertion',
        Gastrointestinal: 'No nausea',
        Neurological: 'No headache',
        Musculoskeletal: 'Myalgia',
        Dermatological: 'No rash',
      },
    },
    examinationFindings: {
      generalAppearance: 'Febrile, toxic look',
      vitalSigns: {
        bloodPressure: '120/70 mmHg',
        heartRate: '105 bpm',
        respiratoryRate: '24/min',
        temperature: '102°F',
        oxygenSaturation: '94%',
        weight: '70 kg',
        height: '175 cm',
        bmi: '22.9',
      },
      systemicExamination: {
        cardiovascular: 'Tachycardia',
        respiratory: 'Right lower lobe crackles',
        gastrointestinal: 'Soft',
        neurological: 'Alert',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-005',
        type: 'Imaging',
        name: 'Chest X-ray',
        result: 'Right lower lobe consolidation',
        normalRange: '',
        date: today,
        interpretation: 'Consistent with pneumonia',
      },
      {
        id: 'inv-006',
        type: 'Lab',
        name: 'TLC',
        result: '15,000 /mm³',
        normalRange: '4,000-11,000 /mm³',
        date: today,
        interpretation: 'Leukocytosis',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Community Acquired Pneumonia',
      differentialDiagnoses: ['Bronchitis', 'Pulmonary TB', 'Lung Abscess'],
      treatmentPlan: 'Oral Amoxicillin-Clavulanate for 7 days',
      medications: [
        { name: 'Amoxicillin-Clavulanate', dose: '625mg', frequency: 'Three times daily', duration: '7 days' },
      ],
      followUp: 'Repeat chest X-ray in 6 weeks',
      prognosis: 'Excellent',
      learningPoints: [
        'Typical CAP presentation',
        'Importance of chest X-ray',
        'Outpatient management',
      ],
    },
  },
  {
    id: 'case-004',
    title: 'Acute Appendicitis',
    specialty: 'Gastroenterology',
    status: 'Draft' as const,
    tags: ['Appendicitis', 'Abdomen', 'Surgery'],
    difficulty: 'Intermediate',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-004',
      age: 22,
      gender: 'Female',
      occupation: 'Student',
      location: 'Delhi',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Right lower abdominal pain for 12 hours',
      historyOfPresentingIllness: 'Pain started periumbilically, then shifted to RLQ. Associated with nausea and vomiting.',
      pastMedicalHistory: [],
      familyHistory: 'None',
      socialHistory: 'No smoking, no alcohol',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {
        Cardiovascular: 'No pain',
        Respiratory: 'No symptoms',
        Gastrointestinal: 'Vomiting twice',
        Neurological: 'No symptoms',
        Musculoskeletal: 'No pain',
        Dermatological: 'Normal',
      },
    },
    examinationFindings: {
      generalAppearance: 'Lying still, uncomfortable',
      vitalSigns: {
        bloodPressure: '110/70 mmHg',
        heartRate: '95 bpm',
        respiratoryRate: '18/min',
        temperature: '99.8°F',
        oxygenSaturation: '99%',
        weight: '55 kg',
        height: '158 cm',
        bmi: '22.0',
      },
      systemicExamination: {
        cardiovascular: 'Normal',
        respiratory: 'Normal',
        gastrointestinal: 'Tenderness at McBurney point, positive Rovsing sign',
        neurological: 'Normal',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-007',
        type: 'Lab',
        name: 'TLC',
        result: '13,500 /mm³',
        normalRange: '4,000-11,000 /mm³',
        date: today,
        interpretation: 'Leukocytosis',
      },
      {
        id: 'inv-008',
        type: 'Imaging',
        name: 'USG Abdomen',
        result: 'Appendiceal wall thickening',
        normalRange: '',
        date: today,
        interpretation: 'Suggestive of appendicitis',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Acute Appendicitis',
      differentialDiagnoses: ['Ovarian cyst', 'UTI', 'Gastroenteritis'],
      treatmentPlan: 'Laparoscopic appendectomy',
      medications: [],
      followUp: 'Surgical follow-up in 1 week',
      prognosis: 'Excellent post-surgery',
      learningPoints: [
        'Classic migratory pain',
        'Abdominal signs',
        'Surgical management',
      ],
    },
  },
  {
    id: 'case-005',
    title: 'Ischemic Stroke with Left Hemiparesis',
    specialty: 'Neurology',
    status: 'Published' as const,
    tags: ['Stroke', 'CVA', 'Hemiparesis'],
    difficulty: 'Advanced',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-005',
      age: 67,
      gender: 'Male',
      occupation: 'Retired',
      location: 'Ghaziabad',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Sudden weakness of left side of body for 3 hours',
      historyOfPresentingIllness: 'Sudden onset left arm and leg weakness while watching TV. Slurred speech.',
      pastMedicalHistory: ['Hypertension', 'Atrial Fibrillation'],
      familyHistory: 'Brother had stroke',
      socialHistory: 'Ex-smoker (quit 5 years ago)',
      allergies: [],
      currentMedications: ['Atenolol 50mg', 'Warfarin 2mg'],
      reviewOfSystems: {
        Cardiovascular: 'No chest pain',
        Respiratory: 'No dyspnea',
        Gastrointestinal: 'No symptoms',
        Neurological: 'Weakness left side',
        Musculoskeletal: 'No pain',
        Dermatological: 'Normal',
      },
    },
    examinationFindings: {
      generalAppearance: 'Alert, slurred speech',
      vitalSigns: {
        bloodPressure: '170/95 mmHg',
        heartRate: '98 bpm (irregular)',
        respiratoryRate: '18/min',
        temperature: '98.8°F',
        oxygenSaturation: '96%',
        weight: '80 kg',
        height: '172 cm',
        bmi: '27.1',
      },
      systemicExamination: {
        cardiovascular: 'Irregularly irregular',
        respiratory: 'Clear',
        gastrointestinal: 'Soft',
        neurological: 'Left hemiparesis 3/5 power',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-009',
        type: 'Imaging',
        name: 'CT Brain',
        result: 'No hemorrhage, right MCA territory hypodensity',
        normalRange: '',
        date: today,
        interpretation: 'Acute ischemic stroke',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Acute Ischemic Stroke (Right MCA)',
      differentialDiagnoses: ['Intracerebral hemorrhage', 'Todd paralysis', 'Hypoglycemia'],
      finalDiagnosis: 'Acute Ischemic Stroke',
      treatmentPlan: 'Thrombolysis (within window), Aspirin, Rehabilitation',
      medications: [
        { name: 'Aspirin', dose: '150mg', frequency: 'Once daily', duration: 'Lifelong' },
        { name: 'Atorvastatin', dose: '40mg', frequency: 'Once daily', duration: 'Ongoing' },
      ],
      followUp: 'Neurology and physiotherapy follow-up',
      prognosis: 'Depends on rehabilitation',
      learningPoints: [
        'Time is brain',
        'FAST assessment',
        'Secondary prevention',
      ],
    },
  },
  {
    id: 'case-006',
    title: 'Hypothyroidism Presentation',
    specialty: 'Endocrinology',
    status: 'In Progress' as const,
    tags: ['Hypothyroidism', 'TSH', 'Levothyroxine'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-006',
      age: 38,
      gender: 'Female',
      occupation: 'Designer',
      location: 'Faridabad',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Fatigue, weight gain, and cold intolerance for 3 months',
      historyOfPresentingIllness: 'Gradual onset tiredness, weight gain of 8 kg despite reduced appetite, feeling cold all the time.',
      pastMedicalHistory: [],
      familyHistory: 'Mother has hypothyroidism',
      socialHistory: 'No smoking, no alcohol',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {
        Cardiovascular: 'No pain',
        Respiratory: 'No symptoms',
        Gastrointestinal: 'Constipation',
        Neurological: 'Tiredness',
        Musculoskeletal: 'Muscle aches',
        Dermatological: 'Dry skin',
      },
    },
    examinationFindings: {
      generalAppearance: 'Puffy face, dry skin',
      vitalSigns: {
        bloodPressure: '110/70 mmHg',
        heartRate: '60 bpm',
        respiratoryRate: '16/min',
        temperature: '97.2°F',
        oxygenSaturation: '98%',
        weight: '72 kg',
        height: '162 cm',
        bmi: '27.4',
      },
      systemicExamination: {
        cardiovascular: 'Bradycardia',
        respiratory: 'Normal',
        gastrointestinal: 'Soft',
        neurological: 'DTRs delayed relaxation',
        musculoskeletal: 'Normal',
        dermatological: 'Dry, cool skin',
      },
    },
    investigations: [
      {
        id: 'inv-010',
        type: 'Lab',
        name: 'TSH',
        result: '12.5 mIU/L',
        normalRange: '0.5-4.5 mIU/L',
        date: today,
        interpretation: 'Elevated TSH',
      },
      {
        id: 'inv-011',
        type: 'Lab',
        name: 'Free T4',
        result: '0.6 ng/dL',
        normalRange: '0.8-1.8 ng/dL',
        date: today,
        interpretation: 'Low free T4',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Primary Hypothyroidism',
      differentialDiagnoses: ['Depression', 'Chronic Fatigue Syndrome', 'Anemia'],
      treatmentPlan: 'Levothyroxine replacement',
      medications: [
        { name: 'Levothyroxine', dose: '50mcg', frequency: 'Once daily', duration: 'Ongoing' },
      ],
      followUp: 'TSH check in 6 weeks',
      prognosis: 'Excellent with replacement',
      learningPoints: [
        'Symptoms of hypothyroidism',
        'TSH first line test',
        'Lifelong replacement',
      ],
    },
  },
  {
    id: 'case-007',
    title: 'Acute Gastroenteritis',
    specialty: 'Gastroenterology',
    status: 'Published' as const,
    tags: ['Diarrhea', 'Vomiting', 'Dehydration'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-007',
      age: 28,
      gender: 'Male',
      occupation: 'Software Engineer',
      location: 'Gurugram',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Diarrhea and vomiting for 1 day',
      historyOfPresentingIllness: 'Multiple episodes of watery diarrhea and vomiting after eating outside food.',
      pastMedicalHistory: [],
      familyHistory: 'None',
      socialHistory: 'No smoking, social drinker',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {
        Cardiovascular: 'No pain',
        Respiratory: 'No symptoms',
        Gastrointestinal: 'Diarrhea and vomiting',
        Neurological: 'Mild dizziness',
        Musculoskeletal: 'Weakness',
        Dermatological: 'Normal',
      },
    },
    examinationFindings: {
      generalAppearance: 'Mild dehydration',
      vitalSigns: {
        bloodPressure: '100/60 mmHg',
        heartRate: '100 bpm',
        respiratoryRate: '18/min',
        temperature: '99.5°F',
        oxygenSaturation: '99%',
        weight: '68 kg',
        height: '173 cm',
        bmi: '22.7',
      },
      systemicExamination: {
        cardiovascular: 'Tachycardia',
        respiratory: 'Normal',
        gastrointestinal: 'Hyperactive bowel sounds',
        neurological: 'Alert',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-012',
        type: 'Lab',
        name: 'Stool Routine',
        result: 'Pus cells 2-3/hpf',
        normalRange: '0-1/hpf',
        date: today,
        interpretation: 'Suggestive of infection',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Acute Gastroenteritis',
      differentialDiagnoses: ['Food poisoning', 'IBS flare', 'Inflammatory bowel disease'],
      treatmentPlan: 'ORS, probiotics, zinc',
      medications: [
        { name: 'ORS', dose: 'As needed', frequency: 'Ongoing', duration: '2 days' },
        { name: 'Probiotic', dose: '1 capsule', frequency: 'Once daily', duration: '5 days' },
      ],
      followUp: 'If symptoms persist >48 hours',
      prognosis: 'Excellent',
      learningPoints: [
        'Hydration first',
        'ORS use',
        'Usually self-limiting',
      ],
    },
  },
  {
    id: 'case-008',
    title: 'Anxiety Disorder with Panic Attacks',
    specialty: 'Psychiatry',
    status: 'Draft' as const,
    tags: ['Anxiety', 'Panic', 'Psychology'],
    difficulty: 'Intermediate',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    patientDetails: {
      patientId: 'PT-2024-008',
      age: 32,
      gender: 'Female',
      occupation: 'Marketing Manager',
      location: 'New Delhi',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Recurrent episodes of sudden fear and palpitations',
      historyOfPresentingIllness: 'Episodes of intense fear, palpitations, sweating, feeling of impending doom lasting 10-15 minutes.',
      pastMedicalHistory: [],
      familyHistory: 'Mother has anxiety',
      socialHistory: 'High stress job, no smoking, occasional alcohol',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {
        Cardiovascular: 'Palpitations',
        Respiratory: 'Shortness of breath during episodes',
        Gastrointestinal: 'No symptoms',
        Neurological: 'Dizziness during episodes',
        Musculoskeletal: 'Tremors',
        Dermatological: 'Sweating',
      },
    },
    examinationFindings: {
      generalAppearance: 'Anxious but cooperative',
      vitalSigns: {
        bloodPressure: '125/80 mmHg',
        heartRate: '85 bpm',
        respiratoryRate: '18/min',
        temperature: '98.6°F',
        oxygenSaturation: '98%',
        weight: '58 kg',
        height: '163 cm',
        bmi: '21.8',
      },
      systemicExamination: {
        cardiovascular: 'Normal S1 S2',
        respiratory: 'Clear',
        gastrointestinal: 'Soft',
        neurological: 'Normal',
        musculoskeletal: 'Normal',
        dermatological: 'Normal',
      },
    },
    investigations: [
      {
        id: 'inv-013',
        type: 'Lab',
        name: 'Thyroid Profile',
        result: 'Normal',
        normalRange: '',
        date: today,
        interpretation: 'Normal',
      },
      {
        id: 'inv-014',
        type: 'Lab',
        name: 'ECG',
        result: 'Normal sinus rhythm',
        normalRange: '',
        date: today,
        interpretation: 'Normal',
      },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: 'Panic Disorder',
      differentialDiagnoses: ['Hyperthyroidism', 'Pheochromocytoma', 'Mitral valve prolapse'],
      treatmentPlan: 'CBT + SSRI',
      medications: [
        { name: 'Escitalopram', dose: '10mg', frequency: 'Once daily', duration: 'Ongoing' },
      ],
      followUp: 'Psychiatry follow-up monthly',
      prognosis: 'Good with treatment',
      learningPoints: [
        'Panic attack symptoms',
        'Rule out medical causes',
        'CBT is effective',
      ],
    },
  },
];

export const CASE_TEMPLATES: MedicalCase[] = [
  {
    id: 'template-001',
    title: 'Acute Myocardial Infarction Template',
    specialty: 'Cardiology',
    status: 'Draft' as const,
    tags: ['STEMI', 'Template'],
    difficulty: 'Intermediate',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Male',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Chest pain',
      historyOfPresentingIllness: '',
      pastMedicalHistory: ['Hypertension', 'Diabetes'],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Lab', name: 'Troponin', result: '', normalRange: '<0.04 ng/mL', date: today, interpretation: '' },
      { id: generateId(), type: 'Imaging', name: 'ECG', result: '', normalRange: '', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-002',
    title: 'Type 2 Diabetes Template',
    specialty: 'Endocrinology',
    status: 'Draft' as const,
    tags: ['DM2', 'Template'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Male',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Polyuria, polydipsia',
      historyOfPresentingIllness: '',
      pastMedicalHistory: [],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Lab', name: 'FBS', result: '', normalRange: '70-100 mg/dL', date: today, interpretation: '' },
      { id: generateId(), type: 'Lab', name: 'HbA1c', result: '', normalRange: '4-5.6%', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-003',
    title: 'Community Acquired Pneumonia Template',
    specialty: 'Pulmonology',
    status: 'Draft' as const,
    tags: ['CAP', 'Template'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Male',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Cough, fever',
      historyOfPresentingIllness: '',
      pastMedicalHistory: [],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Imaging', name: 'Chest X-ray', result: '', normalRange: '', date: today, interpretation: '' },
      { id: generateId(), type: 'Lab', name: 'TLC', result: '', normalRange: '4000-11000/mm³', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-004',
    title: 'Acute Appendicitis Template',
    specialty: 'Gastroenterology',
    status: 'Draft' as const,
    tags: ['Appendicitis', 'Template'],
    difficulty: 'Intermediate',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Male',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Right lower abdominal pain',
      historyOfPresentingIllness: '',
      pastMedicalHistory: [],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Lab', name: 'TLC', result: '', normalRange: '4000-11000/mm³', date: today, interpretation: '' },
      { id: generateId(), type: 'Imaging', name: 'USG Abdomen', result: '', normalRange: '', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-005',
    title: 'Ischemic Stroke Template',
    specialty: 'Neurology',
    status: 'Draft' as const,
    tags: ['Stroke', 'Template'],
    difficulty: 'Advanced',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Male',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Weakness, slurred speech',
      historyOfPresentingIllness: '',
      pastMedicalHistory: ['Hypertension'],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Imaging', name: 'CT Brain', result: '', normalRange: '', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-006',
    title: 'Hypothyroidism Template',
    specialty: 'Endocrinology',
    status: 'Draft' as const,
    tags: ['Hypothyroidism', 'Template'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Female',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Fatigue, weight gain',
      historyOfPresentingIllness: '',
      pastMedicalHistory: [],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Lab', name: 'TSH', result: '', normalRange: '0.5-4.5 mIU/L', date: today, interpretation: '' },
      { id: generateId(), type: 'Lab', name: 'Free T4', result: '', normalRange: '0.8-1.8 ng/dL', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-007',
    title: 'Acute Gastroenteritis Template',
    specialty: 'Gastroenterology',
    status: 'Draft' as const,
    tags: ['Diarrhea', 'Template'],
    difficulty: 'Beginner',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Male',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Diarrhea, vomiting',
      historyOfPresentingIllness: '',
      pastMedicalHistory: [],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
  {
    id: 'template-008',
    title: 'Anxiety Disorder Template',
    specialty: 'Psychiatry',
    status: 'Draft' as const,
    tags: ['Anxiety', 'Template'],
    difficulty: 'Intermediate',
    authorId: DEFAULT_AUTHOR.id,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    patientDetails: {
      patientId: '',
      age: 0,
      gender: 'Female',
      occupation: '',
      location: '',
      presentingDate: today,
    },
    medicalHistory: {
      chiefComplaint: 'Anxiety, palpitations',
      historyOfPresentingIllness: '',
      pastMedicalHistory: [],
      familyHistory: '',
      socialHistory: '',
      allergies: [],
      currentMedications: [],
      reviewOfSystems: {},
    },
    examinationFindings: {
      generalAppearance: '',
      vitalSigns: {
        bloodPressure: '',
        heartRate: '',
        respiratoryRate: '',
        temperature: '',
        oxygenSaturation: '',
        weight: '',
        height: '',
        bmi: '',
      },
      systemicExamination: {
        cardiovascular: '',
        respiratory: '',
        gastrointestinal: '',
        neurological: '',
        musculoskeletal: '',
        dermatological: '',
      },
    },
    investigations: [
      { id: generateId(), type: 'Lab', name: 'Thyroid Profile', result: '', normalRange: '', date: today, interpretation: '' },
    ],
    diagnosisAndPlan: {
      provisionalDiagnosis: '',
      differentialDiagnoses: [],
      treatmentPlan: '',
      medications: [],
      followUp: '',
      prognosis: '',
      learningPoints: [],
    },
  },
];
